### PR TITLE
Make L1DB description consistent with DPDD.

### PR DESCRIPTION
**Pull request by ktlim**

### CODE REVIEW

**Comment by womullan** [comment]
should probably go for v4 in the change log .

**Comment by womullan** [comment]
in Section 3 -- dont we have a requirements document for DB now (LDM-555 ??)  should that be refereed to here ?

**Comment by womullan** [comment]
Section 3.3. - LDM-55 is refered here .. should be sooner. This first paragraph is very loaded in terms of understanding the db is sharded .. otherwise replicating the small metadata makes no sense .. plus as I have pointed out that is a limitation of mysql many other datbases would not make you replicate that data

**Comment by womullan** [comment]
GAIA --> Gaia its not an acronym

**Comment by womullan** [comment]
Is discussion really - design considerations ?  3.4.1. Implicaitons .. is not a really good heading .. is it Implications of assumptions on requirements in the design ?

**Comment by womullan** [comment]
Section 4... bullet one -- obvious questions which off the shelf RDBMS and when to decide ..

**Comment by timj** [comment]
I set the version number of document as part of the release process. No need to worry about it in drafts. This follows LPM-51 process.

**Comment by womullan** [comment]
looking down in 4.3.6.1 an some other areas you refer to no papers.. there is prior art on zones etc like "There Goes the Neighborhood:  
Relational Algebra for Spatial Data Search " from Jim Gray.   
And 4.3.6.4 Spherical geometry  partitioning did exist in SKyServer in 2013 .. and before

**Comment by womullan** [comment]
5.8.1   I would say "at least" two database releases ..

**Comment by womullan** [comment]
5.10.2 . last line - existing prototype .. some people think you throw away prototypes .. I think its the current implementation  which is pretty much also what 5.16 says.

**Comment by womullan** [comment]
5.16 -- perhaps obvious but important and I would add it here  - exposure of QSERV to astronomy users to gather their reactions to syntax and ability of the system.

**Pull request merged**
